#! /bin/sh

#  TODO(Jesse): Incorporate \uf1db - Rebellion symbol

. panel_colors

num_mon=$(bspc query -M | wc -l)

echo " Initializing .."

while read -r line ; do
  case $line in

    S*)
      # System Info
      sys_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
    ;;
    T*)
    #   # xtitle output
    #   # title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
    ;;
    W*) # BSPWM Message

      wm_info=""
      MonitorsEnumerated=0

      IFS=':' # Change read/param expansion to split on colons

      # Strip the W
      set -- ${line#?}


      while [ $# -gt 0 ] ; do
        item=$1
        name=" ${item#?} " # Add spaces for visual padding and strip first char
        delim=" "

        Underline=$NULL
        Foreground=$OPAQ$GREY
        Background=$TRANSP$BACKGROUND

        case $item in

          M*) # Focused monitor
            [ $MonitorsEnumerated -gt 0 ] && wm_info="${wm_info}   "
            MonitorsEnumerated=$(expr $MonitorsEnumerated + 1)
            MonitorFocused=1

            Underline=$PURPLE_UNDERLINE
            Foreground=$PURPLE_UNDERLINE
          ;;

          m*) # Focused Monitor
            [ $MonitorsEnumerated -gt 0 ] && wm_info="${wm_info}   "
            MonitorsEnumerated=$(expr $MonitorsEnumerated + 1)
            MonitorFocused=0
          ;;

          [F,U]*) # Active Free, Focused Urgent
            if [ $MonitorFocused -eq 1 ]; then
              Underline=$PINK_UNDERLINE
              Foreground=$OPAQ$BLUE
            fi
          ;;

          O*) # Active Occupied
            Foreground=$OPAQ$BLUE
            if [ $MonitorFocused -eq 1 ]; then
              Underline=$PINK_UNDERLINE
            fi
          ;;

          o*) # Inactive Occupied
            Foreground=$OPAQ$BLUE
          ;;

          f*) # Inactive Free
          ;;

          u*) # Inactive Urgent
          ;;

          *) # Eat unwanted messages
            name=""
            delim=""
            Underline=$NULL
            Background=$TRANSP$BACKGROUND
            Foreground=$NULL
          ;;

        esac

        wm_info="${wm_info}%{F$Foreground}%{B$Background}%{U$Underline}%{+u}${name}%{-u}%{B-}%{F-}${delim}"

        shift
      done
    ;;
  esac

  echo "%{l}${wm_info}%{c}%{r}${sys_info}"

done
